SECRET_KEY = "change-this-in-production"
SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False

MAX_LOGIN_ATTEMPTS = 5
FILE_ENCRYPTION_KEY = b'YtiALIQdI4HM-KTiWihZ3ipdQiQiLY49En14mQQXdyY='
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True      # HTTPS only
SESSION_COOKIE_SAMESITE = 'Lax'
PERMANENT_SESSION_LIFETIME = 21600  # 6 Hours
import os

SECRET_KEY = os.environ.get("SECRET_KEY")
FILE_ENCRYPTION_KEY = os.environ.get("FILE_ENCRYPTION_KEY")

SQLALCHEMY_DATABASE_URI = os.environ.get(
    "DATABASE_URL", "sqlite:///db.sqlite3"
)

SQLALCHEMY_TRACK_MODIFICATIONS = False
